[project]
name = "stock-prediction-portal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "djangorestframework>=3.16.0",
    "p>=1.5.0",
    "pillow>=11.3.0",
    "python-decouple>=3.8",
]
